### ISSUE TITLE
Inline pictures are not rendering on FAQ on State ILI page

### ISSUE THREAD

**Issue by craigjmcgowan** [cdcepi/web_tracker#17] opened 2017-11-21 19:47 UTC
I put together an FAQ page for both challenges with some pictures illustrating different parts of the visualizations. The images are displaying on the FluSight page, but not the State FluSight page - there's just a link to download the file rather than the in-line image.

**Comment by cdc-mgz4** [comment] 2017-11-21 20:05
The issue is the space in the URL. State-flusight 2017-18 has a space. A workaround for now is to URL encode the space to state-flusight%202017-18. I've corrected all links for the project. Please leave this issue open as something to work on. Although it may be better to move this to Gitlab.

**Comment by craigjmcgowan** [comment] 2017-11-21 20:12
ah, got it. I'll make sure I don't have any spaces in future files. I don't think this is an urgent issue with that simple work-around but if you want to leave it open that's fine

**Comment by cdc-mgz4** [comment] 2017-11-21 20:14
For this issue the project name has a space. Which means you have to be very mindful when uploading images even if the file name itself doesn't have a space.

**Comment by cdc-mgz4** [comment] 2017-11-28 15:47
Moving this issue to gitlab. The title is ok of the original issue but not not very descriptive for a feature request which turned out to be.

**Closed as completed by cdc-mgz4** 2017-11-28 15:47 UTC
Labels: enhancement, help wanted
